apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: infisicalsecrets.secrets.infisical.com
spec:
  group: secrets.infisical.com
  names:
    kind: InfisicalSecret
    listKind: InfisicalSecretList
    plural: infisicalsecrets
    singular: infisicalsecret
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretName:
                  type: string
                data:
                  type: object
                  additionalProperties:
                    type: string

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: infisicalpushsecrets.secrets.infisical.com
spec:
  group: secrets.infisical.com
  names:
    kind: InfisicalPushSecret
    listKind: InfisicalPushSecretList
    plural: infisicalpushsecrets
    singular: infisicalpushsecret
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretName:
                  type: string
                data:
                  type: object
                  additionalProperties:
                    type: string
