---
#https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default 
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 68.1.0
    helm:
      skipCrds: false
      valueFiles:
      - $values/apps/templates/values/prometheus/values.yaml
    chart: kube-prometheus-stack
  - repoURL: 'https://github.com/lefterisALEX/homelabs-hetzner-infra'
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
