apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default 
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - ServerSideApply=true
  source:
    chart: csi-driver-smb
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    targetRevision: 1.16.0
    helm:
      version: v3
