apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: storage-box-hetzner
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        envSlug: prod
        projectSlug: k3s-0oo-y
        secretsPath: "/storagebox"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: kube-system
  managedSecretReference:
    secretName: storagebox
    secretNamespace: kube-system
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: tailscale-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        envSlug: prod
        projectSlug: k3s-0oo-y
        secretsPath: "/tailscale"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: kube-system
  managedSecretReference:
    secretName: operator-oauth
    secretNamespace: tailscale
