apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  source:
    chart: secrets-operator
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
    targetRevision: 0.8.0
    helm:
      version: v3
      parameters:
        - name: installCRDs
          value: "true"
        - name: scopedRBAC
          value: "false"
