---
#https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 41.7.4
    helm:
      skipCrds: true
      values: |
        alertmanager:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              # kubernetes.io/tls-acme: "true"
            labels: {}
            path: /
            pathType: Prefix
            hosts:
              - alertmanager.home
          config:
            route:
              group_by: ['namespace']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: default
              routes:
              - receiver: default
                matchers:
                  - alertname =~ "InfoInhibitor|Watchdog"
        prometheus:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              # kubernetes.io/tls-acme: "true"
            labels: {}
            path: /
            pathType: Prefix
            hosts:
              - prometheus.home
          prometheusSpec:
            retention: 5d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
    chart: kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true