---
#https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 41.7.4
    helm:
      skipCrds: true
      valueFiles:
      - values-prometheus.yaml
    chart: kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
